[package]
id = "linux-wayland-qt-demo"
name = "Linux Wayland Qt Demo"
version = "0.1.0"
source = "apps/linux_wayland_qt_demo"
output = "packages/linux_wayland_qt_demo.rpx"

[app]
entry = "main.rdx"
layout = "main.rml"

[[files]]
src = "QTWLDMO.BIN"
dst = "QTWLDMO.BIN"

[sign]
enabled = true
output = "packages/linux_wayland_qt_demo.rpx.sig"
