[package]
id = "cpp-doom"
name = "CPP-DOOM"
version = "0.1.0"
source = "apps/cpp_doom"
output = "packages/cpp_doom.rpx"

[app]
entry = "main.rdx"
layout = "main.rml"

[[files]]
src = "CPPDOOM.BIN"
dst = "CPPDOOM.BIN"

[sign]
enabled = true
output = "packages/cpp_doom.rpx.sig"
