#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-$ROOT_DIR/third_party/freebsd-src/sys/amd64/linux/linux_syscalls.c}"
OUT="${2:-$ROOT_DIR/kernel/src/linux_sysent.rs}"

if [[ ! -f "$SRC" ]]; then
  echo "error: missing source file: $SRC" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

awk '
BEGIN {
  max = -1;
}
{
  if ($0 !~ /"[^"]+"/) {
    next;
  }
  if ($0 !~ /\/\*[[:space:]]*[0-9]+[[:space:]]*=/) {
    next;
  }

  line = $0;
  name = line;
  sub(/^[^"]*"/, "", name);
  sub(/".*$/, "", name);

  num = line;
  sub(/^.*\/\*[[:space:]]*/, "", num);
  sub(/[[:space:]]*=.*$/, "", num);

  idx = num + 0;
  names[idx] = name;
  if (idx > max) {
    max = idx;
  }
}
END {
  if (max < 0) {
    print "error: no syscall rows parsed" > "/dev/stderr";
    exit 1;
  }
  print "// Auto-generated by scripts/generate_freebsd_linux_sysent.sh";
  print "// Source: third_party/freebsd-src/sys/amd64/linux/linux_syscalls.c";
  print "// Mirrors FreeBSD Linuxulator syscall-number ABI metadata.";
  print "";
  print "pub const FREEBSD_LINUX_ABI_MAX_SYSCALL: u64 = " max ";";
  print "pub static FREEBSD_LINUX_ABI_SYSCALLS: [&str; " (max + 1) "] = [";
  for (i = 0; i <= max; i++) {
    name = names[i];
    if (name == "") {
      name = "#missing";
    }
    gsub(/\\/, "\\\\", name);
    gsub(/\"/, "\\\"", name);
    print "    \"" name "\",";
  }
  print "];";
}
' "$SRC" > "$tmp"

{
  cat "$tmp"
  cat <<'RS'

#[inline]
fn normalize_freebsd_linux_name(raw: &'static str) -> &'static str {
    if raw.starts_with('#') {
        return "nosys";
    }

    match raw {
        "linux_write" => "write",
        "linux_newstat" => "stat",
        "linux_newfstat" => "fstat",
        "linux_newlstat" => "lstat",
        "linux_mmap2" => "mmap",
        "linux_pread" => "pread64",
        "linux_pwrite" => "pwrite64",
        "linux_fadvise64" => "fadvise64",
        "linux_sys_futex" => "futex",
        _ => raw.strip_prefix("linux_").unwrap_or(raw),
    }
}

#[inline]
pub fn freebsd_linux_abi_name(sysno: u64) -> Option<&'static str> {
    if sysno > FREEBSD_LINUX_ABI_MAX_SYSCALL {
        return None;
    }

    let raw = FREEBSD_LINUX_ABI_SYSCALLS[sysno as usize];
    Some(normalize_freebsd_linux_name(raw))
}
RS
} > "$OUT"

echo "Generated: $OUT"
